### ISSUE TITLE
Build error on linux

### ISSUE THREAD

**Issue by fedorov** [chribaue/PETTumorSegmentation#13]
http://slicer.cdash.org/buildSummary.php?buildid=1184598

```
make[5]: *** No rule to make target `/home/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/lib/Slicer-4.9/qt-loadable-modules/libvtkSlicerSegmentationsModuleLogic.so', 
needed by `lib/Slicer-4.9/qt-loadable-modules/libvtkSlicerPETTumorSegmentationModuleMRML.so'.  Stop.
```

cc: @cpinter

**Comment by cpinter** [comment]
I only did additions, so I didn't expect any errors. Investigating now.

**Comment by cpinter** [comment]
Oh this happened with the nightly! So this cannot be related to my recent change. As a matter of fact, there was no change in Segmentations logic for more than 6 weeks

The [Slicer dashboard](http://slicer.cdash.org/viewBuildError.php?buildid=1184036) suggests that Slicer build failed on Linux, for other reasons, but it succeeded yesterday. There is nothing to do I think, but wait for tomorrow's nightly.

**Comment by fedorov** [comment]
Indeed, that was the issue. Sorry for the false alarm!
