### ISSUE TITLE
can i use this code to segment knee cartilage?

### ISSUE THREAD

**Issue by MENG1996** [chribaue/PETTumorSegmentation#15]
Recently I read many Prof. Milan Sonka's papers and I am really interested in LOGISMOS. 
But I did not find the source of LOGISMOS.
I wonder if I can reproduce LOGISMOS according to this code
My English is not very good, please forgive me if I speak stiffly

**Comment by chribaue** [comment]
The PETTumorSegmentation code is based on the LOGISMOS framework and contains all the code describing the method presented in Beichel et al. (2016): "Semiautomated Segmentation of Head and Neck Cancers in 18F-FDG PET Scans: A Just-Enough-Interaction Approach", in Medical Physics. http://dx.doi.org/10.1118/1.4948679.

The PETTumorSegmentation on github does not contain all code for knee cartilage segmentation. That's a different application. But you can still use the PETTumorSegmentation LOGISMOS code as a starting point for your LOGISMOS-related developments.
