### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by BishopWolf** [chribaue/PETTumorSegmentation#21]
When I click in a tumour the extension is not creating segments

**Comment by chribaue** [comment]
The extension only works for certain versions of 3DSlicer. We recommend Slicer 4.10.2, which you can download here: http://slicer.kitware.com/midas3/folder/274

**Comment by BishopWolf** [comment]
Are there plans to upgrade this extension to work on current slicer versions?

**Comment by chribaue** [comment]
Currently, we do not have funding to upgrade this extension.

**Comment by jcfr** [comment]
@chribaue Could you close this issue ?

For future references:

* As of Dec 14th 2021, extension is now available for download (See https://github.com/QIICR/PETTumorSegmentation/issues/16#issuecomment-994088389)
* Legacy editor effect has been removed in favor of the segmentation editor effect.

**Comment by jcfr** [comment]
Additionally the Slicer wiki has been updated to remove the link to the now disabled legacy Editor effect.
See https://www.slicer.org/w/index.php?title=Documentation%2FNightly%2FExtensions%2FPETTumorSegmentation&type=revision&diff=63897&oldid=52420
