### ISSUE TITLE
Using effect and then selecting SegmentEditor "No editing" cursor hides cursor from slice widgets

### ISSUE THREAD

**Issue by che85** [chribaue/PETTumorSegmentation#9]
There is no cursor visible after using this effect

**Comment by chribaue** [comment]
@che85 Thank you for reporting. I already identified the problem and will fix it.

**Comment by chribaue** [comment]
fixed in : https://github.com/QIICR/PETTumorSegmentation/commit/fe01e7bf5f8a259343d5214fad870d70889d636d
